import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/header";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-screen bg-darkblue`}
      >
        <div className="w-[80%] max-w-[1440px] h-[85vh] rounded-3xl absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 flex overflow-hidden after:content-[''] after:absolute after:inset-0 after:bg-lowBlue-liner after:z-[-1] after:opacity-80 after:blur-3xl">
          <Header />
          <div className="w-full p-5 pl-0">{children}</div>
        </div>
      </body>
    </html>
  );
}
